-- SCORPION WORKOUTS - ESQUEMA PRINCIPAL
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',role text not null default 'student' check(role in('admin','coach','student')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.plans(id uuid primary key default gen_random_uuid(),name text not null,price numeric(12,2) not null default 0,description text,features jsonb not null default '[]'::jsonb,popular boolean not null default false,active boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.students(id uuid primary key default gen_random_uuid(),user_id uuid unique references auth.users(id) on delete cascade,full_name text not null,email text,plan_id uuid references public.plans(id) on delete set null,goal text,start_date date,next_payment_date date,notes text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.exercises(id uuid primary key default gen_random_uuid(),name text not null,muscle_group text,equipment text,video_url text,instructions text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.routines(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,name text not null,active boolean not null default true,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.routine_days(id uuid primary key default gen_random_uuid(),routine_id uuid not null references public.routines(id) on delete cascade,day_number int not null,title text not null,created_at timestamptz not null default now());
create table if not exists public.routine_exercises(id uuid primary key default gen_random_uuid(),routine_day_id uuid not null references public.routine_days(id) on delete cascade,exercise_id uuid references public.exercises(id) on delete set null,name text,sets int not null default 3,reps text not null default '8-10',rest_seconds int not null default 90,notes text,video_url text,position int not null default 0,created_at timestamptz not null default now());
create table if not exists public.exercise_logs(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,routine_day_id uuid references public.routine_days(id) on delete set null,routine_exercise_id uuid not null references public.routine_exercises(id) on delete cascade,workout_date date not null,set_number int not null,weight numeric(8,2),reps int,completed boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(student_id,workout_date,routine_exercise_id,set_number));
create table if not exists public.workout_feedback(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,routine_day_id uuid references public.routine_days(id) on delete set null,workout_date date not null,rpe int check(rpe between 1 and 10),comment text,completed boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(student_id,workout_date,routine_day_id));
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,amount numeric(12,2) not null,due_date date not null,status text not null default 'pending' check(status in('paid','pending','overdue')),paid_at timestamptz,concept text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_students_user on public.students(user_id);create index if not exists idx_routines_student on public.routines(student_id);create index if not exists idx_logs_student_date on public.exercise_logs(student_id,workout_date);create index if not exists idx_payments_student_due on public.payments(student_id,due_date);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,role)values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'role','student')) on conflict(id)do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
